feat: Initial implementation of many GCD API's using Swift Concurrency (#1)
* chore: refine gitignore

* chore: Set up initial swift package manifest file.

* feat: Implement DispatchQueue using Swift Concurrency.

* feat: Implement DispatchGroup using Swift Concurrency.

* feat: Implement DispatchSemaphore using Swift Concurrency.

* feat: Implement DispatchTime using Swift Concurrency.

* feat: Implement DispatchTimeInterval using Swift Concurrency.

* chore: Add some basic testing.

* chore: Update Readme.

* ci: Add pull request CI workflows.

* chore: Silence some lint that is intentionally written this way to match constansts in libDispatch.

* ci: Disable api breakage check for now.

* ci: Don't test swift versions before 6.1

* chore: Update file headers

* chore: Changing wording in readme.

* chore: Ignore missing license header in Package.swift file.

* chore: Clean up lint a different way.

* ci: update test targets

* ci: Add wasm sdk installation script.

* chore: Fix license header format in bash script.

* chore: Update swift-format rules.

* chore: Add convenience scripts to run the same commands CI uses for swift-format and swift-lint.

* chore: Fix license setup for soundness checks.

* chore: Removing lint rule definitions not recognized by github online swift-format version.

* ci: Don't run tests on Swift 5.10 either. Not supported.

* fix: Fix potential main thread issue in DispatchQueue that currently only seems to show up in linux.

* ci: Try a slightly different mechanism to get the swift version, to attempt to resolve issues showing up in CI for wasm builds.

* chore: update scripting

* chore: Fix lint that CI wants one way, and local install wants a different way. CI will have to win on this one for now.

* ci: Use my own bash adapted from Yuta Saito's open MR to build wasm for now.

* ci: move scripts inline to yml configuration to work around issues with script pathing in CI.

* test: Update unit tests to adjust expectations for linux targets. Linux doesn't run main actor on the main thread, so the expectation was not correct. Adjusted expectations.

* ci: Install jq for wasm builds.

* fix: Fix unit test expectations for linux. Take two.

* chore: lint

* ci: wasm build needs to clone the code before it can build.

* ci: use Swift 6.1 for wasm build.

* ci: Specifical swift 6.1.0 for wasm builds, not swift 6.1.2.

* chore: Fix incomplete comment.

* fix: Fix a variety of issues found in DispatchAsync while implementing new tests.

* chore: Use swift version 6.0 as the minimum rather than 6.1.

* refactor: Update ifdefs and @_spi guards to allow development against traditional iOS targets, but to elide exact Dispatch api replacements for any current or future target that does not include Dispatch.

* refactor: Change copyright owner to PassiveLogic for now.

* chore: Run swift-format

* chore: Add permalink to copy-pasted file.

* docs: Add usage notes with plenty of warnings.

* docs: Add info about license.

* ci: Disable license header check in CI for now.

* chore: See if this address weird lint issue popping up in CI.

* chore: Address lint error for Package.swift:19:15: error: expected value in function call

* ci: Use a later version of swift for the swift-format check. This shoudl resolve discrepancies between local swift-format and CI-based swift-format.

* ci: Updating swift-format rule for swift 6.1.0 instead of swift 6.2.

* chore: Update a few more file headers.

* chore: Update swift to Swift in comments

Co-authored-by: Mark Pospesel <mark@crazymilksoftware.com>

* chore: update more swift vs Swift language

* chore: Parameterize number of iterations for critical unit test.

* chore: Fix typo.

* refactor: rename package to follow existing patterns in Apple's Swift repositories, to make this as easy as possible for them to adopt.

* chore: refine documentation.